language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t cgsteib/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cgsteib/docker-react npm run test -- --coverage

